table _mesures
	lineageTag: abfdc7b4-3115-461b-aaaa-60dba1148843

	measure CA = SUMX(orders, orders[revenue])
		formatString: #,0
		displayFolder: CA
		lineageTag: e7c1327e-3273-4690-a5eb-ae1e9bdea167

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CA_12DerniersMois = ```
			
			VAR Fin = DATE(2018,3,31) --TODAY() le dataset s'arrête au 31/03/2018, je fais comme si c'est aujourd'hui
			VAR Debut = EDATE(Fin, -12)+1
			VAR Calcul =
			    CALCULATE(
			        [CA],
			        orders[order_date] >= Debut && orders[order_date] <= Fin
			    )
			VAR Result =
			    IF(     
			        MAX(dimdates[Date]) < Debut,
			        BLANK(),  -- Masque les valeurs avant la période
			        Calcul
			    )
			RETURN  Result
			```
		formatString: #,0
		displayFolder: CA
		lineageTag: 033ce580-1fa8-42d1-b1f4-d2925726bc8a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CA_indicateur_prog% = ```
			
			 --utilisé pour faire des mises en forme conditionnelles sur +10% ou -10%
			SWITCH(
			    TRUE(),
			    [CA_M-1prog%] < -0.1, -1,
			    [CA_M-1prog%] > 0.1, 1,
			    0
			)
			```
		formatString: 0
		displayFolder: CA
		lineageTag: 21f7de5c-17e6-474b-ac85-0fddd41795b7

	measure CA_M-1 =
			
			CALCULATE(
			    [CA],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0
		displayFolder: CA
		lineageTag: 03858878-9637-44da-82b0-8c3ed8599fda

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CA_M-1prog = [CA]-[CA_M-1]
		formatString: #,0
		displayFolder: CA
		lineageTag: 04b11ead-41a3-4f7b-86ac-ed1c02b85f08

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CA_M-1prog% = DIVIDE([CA_M-1prog],[CA_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: CA
		lineageTag: d4d3e99a-a0e9-4803-8af7-5e03cd28bff8

		annotation PBI_FormatHint = {"isCustom":true}

	measure NbClients =
			
			CALCULATE(
			    DISTINCTCOUNT(orders[customer_id]),
			    orders[price]>0
			)
		formatString: #,0
		displayFolder: Clients
		lineageTag: 6bef6247-b408-4b41-85ae-49a051677169

	measure NbClients_M-1 =
			
			CALCULATE(
			    [NbClients],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0
		displayFolder: Clients
		lineageTag: 76db2a63-d325-452d-b076-147d2c8394c2

	measure NbClients_M-1prog = [NbClients]-[NbClients_M-1]
		formatString: 0
		displayFolder: Clients
		lineageTag: fd26f4ab-7e5b-460c-af04-9ad70f419d56

	measure NbClients_M-1prog% = DIVIDE([NbClients_M-1prog],[NbClients_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: Clients
		lineageTag: 6d31b528-974c-45bf-bb0d-759e7463653e

		annotation PBI_FormatHint = {"isCustom":true}

	measure PrixMoyen = DIVIDE([CA], [Quantité])
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		displayFolder: PrixMoyen
		lineageTag: adfc7272-1eac-4ffe-a675-55b71800e9ea

	measure PrixMoyen_M-1 =
			
			CALCULATE(
			    [PrixMoyen],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		displayFolder: PrixMoyen
		lineageTag: 8d8dd01e-d93c-4e72-898b-bd8266df46a5

	measure PrixMoyen_M-1prog = [PrixMoyen]-[PrixMoyen_M-1]
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		displayFolder: PrixMoyen
		lineageTag: aebf9664-309b-45dd-ba29-759a768f9398

	measure PrixMoyen_M-1prog% = DIVIDE([PrixMoyen_M-1prog],[PrixMoyen_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: PrixMoyen
		lineageTag: 4f0fbdb6-f95a-4423-a75b-659347683cca

		annotation PBI_FormatHint = {"isCustom":true}

	measure NbProduits =
			
			CALCULATE(
			    DISTINCTCOUNT(orders[product_id]),
			    orders[price]>0
			)
		formatString: 0
		displayFolder: Produits
		lineageTag: 879a58c3-9e26-437f-9152-2b96327c6f90

	measure NbProduits_M-1 =
			
			CALCULATE(
			    [NbProduits],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0
		displayFolder: Produits
		lineageTag: 558f7367-f6c0-4c94-89e8-f3ad70f05865

	measure NbProduits_M-1prog = [NbProduits]-[NbProduits_M-1]
		formatString: 0
		displayFolder: Produits
		lineageTag: 7aea080c-1382-4ac6-b2d9-2f8cb823d062

	measure NbProduits_M-1prog% = DIVIDE([NbProduits_M-1prog],[NbProduits_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: Produits
		lineageTag: b42e9898-4f85-4cc5-972a-093673a45338

		annotation PBI_FormatHint = {"isCustom":true}

	measure Quantité = SUMX(orders, orders[quantity])
		formatString: #,0
		displayFolder: Quantité
		lineageTag: afcd42d4-b4fb-4cfd-aaa1-be6c25a097a3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Quantité_M-1 =
			
			CALCULATE(
			    [Quantité],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0
		displayFolder: Quantité
		lineageTag: 00077239-e2e8-4bc9-aa9f-f78f5e6cd2c7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Quantité_M-1prog = [Quantité]-[Quantité_M-1]
		displayFolder: Quantité
		lineageTag: 6717dffa-ea55-4470-b527-3801679ca6a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Quantité_M-1prog% = DIVIDE([Quantité_M-1prog],[Quantité_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: Quantité
		lineageTag: 82b8aff4-f3ed-4669-ad6d-9922a7b435aa

		annotation PBI_FormatHint = {"isCustom":true}

	column Value
		isHidden
		formatString: 0
		lineageTag: d21bdce3-1a41-4fe6-939e-cfb2eb918998
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition _mesures = calculated
		mode: import
		source = ```
				{ BLANK() }
				
				
				
				```

	annotation PBI_Id = 8bd7260193f04676a976e7eb98130836

