table orders
	lineageTag: 1d824df3-6068-4430-8f2d-d3116a80d602

	measure CA = SUMX(orders, orders[revenue])
		formatString: #,0
		displayFolder: CA
		lineageTag: e7c1327e-3273-4690-a5eb-ae1e9bdea167

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Quantité = SUMX(orders, orders[quantity])
		formatString: #,0
		displayFolder: Quantité
		lineageTag: afcd42d4-b4fb-4cfd-aaa1-be6c25a097a3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure PrixMoyen = DIVIDE([CA], [Quantité])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: PrixMoyen
		lineageTag: adfc7272-1eac-4ffe-a675-55b71800e9ea

	measure NbClients =
			
			CALCULATE(
			    DISTINCTCOUNT(orders[customer_id]),
			    orders[price]>0
			)
		formatString: #,0
		displayFolder: Clients
		lineageTag: 6bef6247-b408-4b41-85ae-49a051677169

	measure CA_M-1 =
			
			CALCULATE(
			    [CA],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0
		displayFolder: CA
		lineageTag: 03858878-9637-44da-82b0-8c3ed8599fda

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CA_M-1prog% = DIVIDE([CA_M-1prog],[CA_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: CA
		lineageTag: d4d3e99a-a0e9-4803-8af7-5e03cd28bff8

		annotation PBI_FormatHint = {"isCustom":true}

	measure CA_M-1prog = [CA]-[CA_M-1]
		formatString: #,0
		displayFolder: CA
		lineageTag: 04b11ead-41a3-4f7b-86ac-ed1c02b85f08

		annotation PBI_FormatHint = {"isDecimal":true}

	measure NbClients_M-1 =
			
			CALCULATE(
			    [NbClients],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0
		displayFolder: Clients
		lineageTag: 76db2a63-d325-452d-b076-147d2c8394c2

	measure NbProduits =
			
			CALCULATE(
			    DISTINCTCOUNT(orders[product_id]),
			    orders[price]>0
			)
		formatString: 0
		displayFolder: Produits
		lineageTag: 879a58c3-9e26-437f-9152-2b96327c6f90

	measure NbProduits_M-1 =
			
			CALCULATE(
			    [NbProduits],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0
		displayFolder: Produits
		lineageTag: 558f7367-f6c0-4c94-89e8-f3ad70f05865

	measure Quantité_M-1 =
			
			CALCULATE(
			    [Quantité],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0
		displayFolder: Quantité
		lineageTag: 00077239-e2e8-4bc9-aa9f-f78f5e6cd2c7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure NbClients_M-1prog = [NbClients]-[NbClients_M-1]
		formatString: 0
		displayFolder: Clients
		lineageTag: fd26f4ab-7e5b-460c-af04-9ad70f419d56

	measure NbProduits_M-1prog = [NbProduits]-[NbProduits_M-1]
		formatString: 0
		displayFolder: Produits
		lineageTag: 7aea080c-1382-4ac6-b2d9-2f8cb823d062

	measure Quantité_M-1prog = [Quantité]-[Quantité_M-1]
		displayFolder: Quantité
		lineageTag: 6717dffa-ea55-4470-b527-3801679ca6a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PrixMoyen_M-1 =
			
			CALCULATE(
			    [PrixMoyen],
			    DATEADD(dimdates[Date], -1, MONTH)
			)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: PrixMoyen
		lineageTag: 8d8dd01e-d93c-4e72-898b-bd8266df46a5

	measure PrixMoyen_M-1prog = [PrixMoyen]-[PrixMoyen_M-1]
		displayFolder: PrixMoyen
		lineageTag: aebf9664-309b-45dd-ba29-759a768f9398

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NbClients_M-1prog% = DIVIDE([NbClients_M-1prog],[NbClients_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: Clients
		lineageTag: 6d31b528-974c-45bf-bb0d-759e7463653e

		annotation PBI_FormatHint = {"isCustom":true}

	measure PrixMoyen_M-1prog% = DIVIDE([PrixMoyen_M-1prog],[PrixMoyen_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: PrixMoyen
		lineageTag: 4f0fbdb6-f95a-4423-a75b-659347683cca

		annotation PBI_FormatHint = {"isCustom":true}

	measure NbProduits_M-1prog% = DIVIDE([NbProduits_M-1prog],[NbProduits_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: Produits
		lineageTag: b42e9898-4f85-4cc5-972a-093673a45338

		annotation PBI_FormatHint = {"isCustom":true}

	measure Quantité_M-1prog% = DIVIDE([Quantité_M-1prog],[Quantité_M-1])
		formatString: +0.0 %;-0.0 %;-
		displayFolder: Quantité
		lineageTag: 82b8aff4-f3ed-4669-ad6d-9922a7b435aa

		annotation PBI_FormatHint = {"isCustom":true}

	measure CA_12DerniersMois = ```
			
			VAR Fin = DATE(2018,3,31) --TODAY() le dataset s'arrête au 31/03/2018, je fais comme si c'est aujourd'hui
			VAR Debut = EDATE(Fin, -12)+1
			VAR Calcul =
			    CALCULATE(
			        [CA],
			        orders[order_date] >= Debut && orders[order_date] <= Fin
			    )
			VAR Result =
			    IF(     
			        MAX(dimdates[Date]) < Debut,
			        BLANK(),  -- Masque les valeurs avant la période
			        Calcul
			    )
			RETURN  Result
			```
		formatString: #,0
		displayFolder: CA
		lineageTag: 033ce580-1fa8-42d1-b1f4-d2925726bc8a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CA_indicateur_prog% =
			
			SWITCH(
			    TRUE(),
			    [CA_M-1prog%] < -0.1, -1,
			    [CA_M-1prog%] > 0.1, 1,
			    0
			)
		formatString: 0
		displayFolder: CA
		lineageTag: 21f7de5c-17e6-474b-ac85-0fddd41795b7

	column order_id
		dataType: string
		lineageTag: 74c20adb-c412-4a85-93d4-fa152fa2f031
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		isHidden
		lineageTag: 0123c4ef-b664-4c6f-b797-2291fe07f8b4
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: string
		isHidden
		lineageTag: aa21cee6-0e42-4f9e-99df-a8cc431e2420
		summarizeBy: none
		sourceColumn: store_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column staff_id
		dataType: string
		isHidden
		lineageTag: ecc15ce4-930b-4157-ad70-c2f6bb27ba79
		summarizeBy: none
		sourceColumn: staff_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		isHidden
		displayFolder: Produits
		lineageTag: 7d5b8d10-819b-4072-94f4-0c99cfeb1d1b
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: int64
		formatString: 0
		lineageTag: df2a2334-eafe-4a86-962b-a4a3d1f8a9a0
		summarizeBy: sum
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		isHidden
		displayFolder: Quantité
		lineageTag: a5b4fbd6-809a-4879-97a2-4f68b8c5de2f
		summarizeBy: sum
		sourceColumn: quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column price
		dataType: double
		isHidden
		lineageTag: dcd34b5c-933c-4a15-aa4e-e654b4a552a6
		summarizeBy: sum
		sourceColumn: price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue
		dataType: double
		isHidden
		lineageTag: a0c08d0a-568a-4572-8582-a98235aa48e1
		summarizeBy: sum
		sourceColumn: revenue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discount_rate
		dataType: double
		lineageTag: 8199b419-b945-466e-9c28-32cf10463cf2
		summarizeBy: sum
		sourceColumn: discount_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column order_date
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 5d121483-d191-4e32-b0fc-01d601a13456
		summarizeBy: none
		sourceColumn: order_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column required_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 27a539c8-ac8f-4ba1-8421-86f52da5165b
		summarizeBy: none
		sourceColumn: required_date

		variation Variation
			isDefault
			relationship: 85224ae5-9216-41e4-a4cb-f18b7dd52c51
			defaultHierarchy: LocalDateTable_9e11f438-3c02-46d6-8e2e-ef73978d3d14.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column shipped_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3606d684-22c4-4fff-a5e6-a80bf3b3074e
		summarizeBy: none
		sourceColumn: shipped_date

		variation Variation
			isDefault
			relationship: c44a1a5c-1e35-4317-b5f6-ae1543bff817
			defaultHierarchy: LocalDateTable_692ea429-557d-4ea1-b6c9-6c2c62546c6b.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition orders = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"high-nature-448517-t4" = Source{[Name="high-nature-448517-t4"]}[Data],
				    local_bike_dbt_Schema = #"high-nature-448517-t4"{[Name="local_bike_dbt",Kind="Schema"]}[Data],
				    mrt_orders_Table = local_bike_dbt_Schema{[Name="mrt_orders",Kind="Table"]}[Data]
				in
				    mrt_orders_Table

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

